{{- if .Values.func.ENABLE_IPSEC_VPN }}
---
kind: VpnGw
apiVersion: vpn-gw.kubecombo.com/v1
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
  name: strongswan
  namespace: {{.Values.namespace}}
spec:
  workloadType: static
  cpu: "1"
  memory: "1024M"
  selector:
    - "kubernetes.io/os: linux"
    {{- if .Values.ipsecvpn.IPSECVPN_NODES_LABEL }}
      {{- with splitList "=" .Values.ipsecvpn.IPSECVPN_NODES_LABEL }}
        {{- if eq (len .) 2 }}
    - "{{ index . 0 }}: {{ index . 1 }}"
        {{- end }}
      {{- end }}
    {{- end }}
  enableIpsecVpn: true
  ipsecEnablePSK: true
  defaultPSK: {{.Values.ipsecvpn.defaultPSK}}
  ipsecVpnImage: {{.Values.global.registry.address}}/{{.Values.global.images.strongswan.repository}}:{{.Values.global.images.strongswan.tag}}
---
kind: IpsecConn
apiVersion: vpn-gw.kubecombo.com/v1
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
  name: mars-moon
  namespace: {{.Values.namespace}}
spec:
  vpnGw: strongswan
  # pubkey use cert-manager x509 ca, support ipv4 ipv6
  # psk use pre shared key, ipv4 only
  auth: {{.Values.ipsecvpn.auth}}
  espProposals: {{.Values.ipsecvpn.espProposals}}
  ikeProposals: {{.Values.ipsecvpn.ikeProposals}}
  # ike version 0, 1, 2
  ikeVersion: "{{.Values.ipsecvpn.ikeVersion}}"
  localVIP: {{.Values.ipsecvpn.localVIP}}
  localEIP: {{.Values.ipsecvpn.localEIP}}
  localPrivateCidrs: {{.Values.ipsecvpn.localPrivateCidrs}}
  remoteEIP: {{.Values.ipsecvpn.remoteEIP}}
  remotePrivateCidrs: {{.Values.ipsecvpn.remotePrivateCidrs}}
{{- end }}
