{{- if .Values.func.ENABLE_IPSEC_VPN }}
---
kind: VpnGw
apiVersion: vpn-gw.kubecombo.com/v1
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
  name: mars
  namespace: {{.Values.namespace}}
spec:
  workloadType: static
  cpu: "1"
  memory: "1024M"
  ipsecEnablePSK: true
  enableIpsecVpn: true
  ipsecVpnImage: {{ .Values.global.registry.address }}/{{ .Values.global.images.strongswan.repository }}:{{ .Values.global.images.strongswan.tag }}
---
kind: IpsecConn
apiVersion: vpn-gw.kubecombo.com/v1
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
  name: mars-moon
  namespace: {{.Values.namespace}}
spec:
  vpnGw: mars
  # pubkey use cert-manager x509 ca, support ipv4 ipv6
  # psk use pre shared key, ipv4 only
  auth: {{ .Values.ipsecvpn.auth }}
  espProposals: {{ .Values.ipsecvpn.espProposals }}
  ikeProposals: {{ .Values.ipsecvpn.ikeProposals }}
  # ike version 0, 1, 2
  ikeVersion: {{ .Values.ipsecvpn.ikeVersion }}
  localCN: mars.vpn.gw.com
  localEIP: {{ .Values.ipsecvpn.localEIP }}
  localPrivateCidrs: {{ .Values.ipsecvpn.localPrivateCidrs }}
  localPSK: {{ .Values.ipsecvpn.localPSK }}
  remotePSK: {{ .Values.ipsecvpn.remotePSK }}
  remoteCN: moon.vpn.gw.com
  remoteEIP: {{ .Values.ipsecvpn.remoteEIP }}
  remotePrivateCidrs: {{ .Values.ipsecvpn.remotePrivateCidrs }}
{{- end }}
