apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-combo-leader-election-rolebinding
  namespace: {{.Values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-combo-leader-election-role
subjects:
  - kind: ServiceAccount
    name: kube-combo-controller-manager
    namespace: {{.Values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-combo-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-combo-manager-role
subjects:
  - kind: ServiceAccount
    name: kube-combo-controller-manager
    namespace: {{.Values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-combo-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-combo-proxy-role
subjects:
  - kind: ServiceAccount
    name: kube-combo-controller-manager
    namespace: {{.Values.namespace}}
