package v1

import "k8s.io/apimachinery/pkg/runtime"

// this should be generated by controller-gen, but not working
// so we write it manually

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pinger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
