# permissions for end users to view debuggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debugger-viewer-role
rules:
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - debuggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - debuggers/status
  verbs:
  - get
