# permissions for end users to edit keepaliveds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keepalived-editor-role
rules:
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - keepaliveds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - keepaliveds/status
  verbs:
  - get
