# permissions for end users to view keepaliveds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keepalived-viewer-role
rules:
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - keepaliveds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - keepaliveds/status
  verbs:
  - get
