# permissions for end users to edit pingers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-combo
    app.kubernetes.io/managed-by: kustomize
  name: pinger-editor-role
rules:
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - pingers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - pingers/status
  verbs:
  - get
