apiVersion: vpn-gw.kubecombo.com/v1
kind: Debug
metadata:
  labels:
    app.kubernetes.io/name: kube-combo
    app.kubernetes.io/managed-by: kustomize
  name: debug-sample
spec:
  # TODO(user): Add fields here
