# permissions for end users to edit vpngws.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpngw-editor-role
rules:
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - vpngws
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - vpngws/status
  verbs:
  - get
