name: Build amd64
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "charts/**"
      - "dist/**"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  push:
    name: Build Kube-Combo
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make docker-build-manager-amd64
          make docker-build-pinger-amd64
