name: Build amd64 Image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  push:
    name: Build Kube-Combo Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          TAG=$(make print-version)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          make docker-build-amd64
          docker images
          docker tag icoy/kube-combo-controller:v$TAG icoy/kube-combo-controller:v$TAG-amd64
          docker push icoy/kube-combo-controller:v$TAG-amd64
