name: Publish Release
on:
  workflow_dispatch:
  schedule:
    - cron: "20 16 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Publish Images
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Publish
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          TAG=$(make print-version)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker pull icoy/kube-combo-controller:$TAG-amd64
          docker pull icoy/kube-combo-controller:$TAG-arm64
          docker manifest create icoy/kube-combo-controller:v$TAG icoy/kube-combo-controller:v$TAG-amd64 icoy/kube-combo-controller:v$TAG-arm64
          docker manifest push icoy/kube-combo-controller:v$TAG
