name: Build Base
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch"
        required: true
        type: choice
        options:
          - main
  schedule:
    - cron: "20 19 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
        branch:
          - main
    name: Build
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        if: (github.event.inputs.branch || matrix.branch) == matrix.branch
        with:
          ref: ${{ matrix.branch }}

      - uses: docker/setup-buildx-action@v3
        if: (github.event.inputs.branch || matrix.branch) == matrix.branch

      - name: Build
        if: (github.event.inputs.branch || matrix.branch) == matrix.branch
        run: |
          VERSION=$(make print-version)
          make docker-build-base-${{ matrix.arch }}
          docker tag icoy/kube-combo-base:v$VERSION icoy/kube-combo-base:v$VERSION-${{ matrix.arch }}
  push:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - main
    needs:
      - build
    name: push
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        if: (github.event.inputs.branch || matrix.branch) == matrix.branch
        with:
          ref: ${{ matrix.branch }}

      - name: Push
        if: (github.event.inputs.branch || matrix.branch) == matrix.branch
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          TAG=$(make print-version)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker images
          docker push icoy/kube-combo-base:v$TAG-amd64
          docker push icoy/kube-combo-base:v$TAG-arm64
          docker manifest create icoy/kube-combo-base:v$TAG icoy/kube-combo-base:v$TAG-amd64 icoy/kube-combo-base:v$TAG-arm64
          docker manifest push icoy/kube-combo-base:v$TAG
